# Pràctica 3: Funcions i Paquets
## 1. Definir funcions i ús de paquets
### 1.1 Funcions

In [1]:
def quadrat(x):
    return(x**2)

In [2]:
quadrat(8)

64

In [3]:
quadrat(11.5)

132.25

In [4]:
def f(x=2,y=5):
    return([x,y,x+y,x*y])

In [5]:
f()

[2, 5, 7, 10]

In [6]:
f(10,20)

[10, 20, 30, 200]

In [7]:
f(y=20)

[2, 20, 22, 40]

In [20]:
def suma(*sumands):
    s=0
    for i in sumands:
        s=s+i
    return s

Només el bucle for es realitzat una vegada fent que la variable i prenga el valor sumands. Si fora un llista o conjunt sumaria cada vegada 

In [21]:
suma(23)

23

In [22]:
suma(1,3,5,7)

16

In [23]:
s

NameError: name 's' is not defined

In [24]:
s=12
print(suma(2,4,6,8))
print(s)

20
12


In [97]:
def g():
    global x
    y = 5
    print("La variable x val", x, "i és global")
    print("La variable y val", y, ", és local i no importa si hi ha una altra y definida fora de la funció")
    x=x*2
    y=y*2
    print("Hem doblat tant la x com la y", x, y)
    return

In [99]:
x = 10
y=99

In [100]:
g()

La variable x val 10 i és global
La variable y val 5 , és local i no importa si hi ha una altra y definida fora de la funció
Hem doblat tant la x com la y 20 10


In [101]:
print(x)
print(y)

20
99


#### 1.1.1 Exemple

In [2]:
def fib(n):
    if n<=0: return
    if n==1: return [1]
    l=[1,1]
    for i in range(n-2):
        l.append(l[-1]+l[-2])
    return l

In [3]:
fib(1)

[1]

In [6]:
fib(10)

[1, 1, 2, 3, 5, 8, 13, 21, 34, 55]

#### 1.1.2 Exercicis

In [8]:
def mcd(m,n):
    r=m%n
    while(r):
        m=n
        n=r
        r=m%n
    return n
        
        

In [10]:
mcd(3,2)

1

In [1]:
def divisors(x):
    l=[]
    for i in range(1,x):
        if(x%i==0):
            l.append(i)
    return l

In [2]:
divisors(1024)

[1, 2, 4, 8, 16, 32, 64, 128, 256, 512]

In [3]:
divisors(4410)

[1,
 2,
 3,
 5,
 6,
 7,
 9,
 10,
 14,
 15,
 18,
 21,
 30,
 35,
 42,
 45,
 49,
 63,
 70,
 90,
 98,
 105,
 126,
 147,
 210,
 245,
 294,
 315,
 441,
 490,
 630,
 735,
 882,
 1470,
 2205]

In [36]:
def separa(s,c):
    contador=0
    contador_acum=0
    z=[]
    for i in range(len(s)):
        if(s[i]==c):
            if(s[contador:i]!=""):
                z.append(s[contador:i])
                contador=i+1
        if(i==len(s)-1):
            z.append(s[contador:i+1])
    return z


    
    

In [38]:
separa("Hola a tothom"," ")

['Hola', 'a', 'tothom']

### 1.2 Ús de paquets
### 1.3 Exemple: el paquete <code> os </code>

In [4]:
import os

In [5]:
os.getcwd()

'/Users/josecalatayud/SageMath/Python'

In [6]:
os

<module 'os' from '/var/tmp/sage-9.4-current/local/lib/python3.9/os.py'>

In [40]:
dir(os)

['CLD_CONTINUED',
 'CLD_DUMPED',
 'CLD_EXITED',
 'CLD_KILLED',
 'CLD_STOPPED',
 'CLD_TRAPPED',
 'DirEntry',
 'EX_CANTCREAT',
 'EX_CONFIG',
 'EX_DATAERR',
 'EX_IOERR',
 'EX_NOHOST',
 'EX_NOINPUT',
 'EX_NOPERM',
 'EX_NOUSER',
 'EX_OK',
 'EX_OSERR',
 'EX_OSFILE',
 'EX_PROTOCOL',
 'EX_SOFTWARE',
 'EX_TEMPFAIL',
 'EX_UNAVAILABLE',
 'EX_USAGE',
 'F_LOCK',
 'F_OK',
 'F_TEST',
 'F_TLOCK',
 'F_ULOCK',
 'GenericAlias',
 'Mapping',
 'MutableMapping',
 'NGROUPS_MAX',
 'O_ACCMODE',
 'O_APPEND',
 'O_ASYNC',
 'O_CLOEXEC',
 'O_CREAT',
 'O_DIRECTORY',
 'O_DSYNC',
 'O_EXCL',
 'O_EXLOCK',
 'O_NDELAY',
 'O_NOCTTY',
 'O_NOFOLLOW',
 'O_NONBLOCK',
 'O_RDONLY',
 'O_RDWR',
 'O_SHLOCK',
 'O_SYNC',
 'O_TRUNC',
 'O_WRONLY',
 'POSIX_SPAWN_CLOSE',
 'POSIX_SPAWN_DUP2',
 'POSIX_SPAWN_OPEN',
 'PRIO_PGRP',
 'PRIO_PROCESS',
 'PRIO_USER',
 'P_ALL',
 'P_NOWAIT',
 'P_NOWAITO',
 'P_PGID',
 'P_PID',
 'P_WAIT',
 'PathLike',
 'RTLD_GLOBAL',
 'RTLD_LAZY',
 'RTLD_LOCAL',
 'RTLD_NODELETE',
 'RTLD_NOLOAD',
 'RTLD_NOW',
 'R_OK',
 '

In [41]:
help(os.mkdir)

Help on built-in function mkdir in module posix:

mkdir(path, mode=511, *, dir_fd=None)
    Create a directory.
    
    If dir_fd is not None, it should be a file descriptor open to a directory,
      and path should be relative; path will then be relative to that directory.
    dir_fd may not be implemented on your platform.
      If it is unavailable, using it will raise a NotImplementedError.
    
    The mode argument is ignored on Windows.



#### 1.3.1 Exemple: el paquet <code>numpy</code>

In [11]:
import numpy as np

In [43]:
print(np.pi)

3.141592653589793


In [44]:
print(np.sin(np.pi))

1.2246467991473532e-16


In [45]:
from numpy import sin,cos,pi

In [46]:
print(cos(pi))

-1.0


In [17]:
import numpy as np

In [18]:
matriuidentitat=np.eye(5)

In [51]:
print(matriuidentitat)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [19]:
matriuuns=np.ones((5,5))

In [20]:
print(matriuuns)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [55]:
print(3*matriuuns-2*matriuidentitat)

[[1. 3. 3. 3. 3.]
 [3. 1. 3. 3. 3.]
 [3. 3. 1. 3. 3.]
 [3. 3. 3. 1. 3.]
 [3. 3. 3. 3. 1.]]


#### 1.3.4 Exercicis
##### (a)

In [56]:
X=np.random.rand(5,6)

In [57]:
print(X)

[[0.22739394 0.61004137 0.31222384 0.61782182 0.10357626 0.54913691]
 [0.64798612 0.44397252 0.50037254 0.9193528  0.06273523 0.18322464]
 [0.07806876 0.63283034 0.18074513 0.13101022 0.93848008 0.73758067]
 [0.28815968 0.29808956 0.12356817 0.15710844 0.09772938 0.16790894]
 [0.43212149 0.88457484 0.70917024 0.91248182 0.39594104 0.76623531]]


L'execusió de la sentencia random.rand(5,6) dona com a resultat un array bidimensional (com una matriu) de dimensions (5,6) i cada una d'aquest posicions conté un nombre aleatòria de [0,1)

In [64]:
X.mean(axis=0)

array([0.334746  , 0.57390173, 0.36521598, 0.54755502, 0.3196924 ,
       0.48081729])

In [65]:
X.mean(axis=1)

array([0.40336569, 0.45960731, 0.44978587, 0.1887607 , 0.68342079])

In [22]:
help(np.mean)

Help on function mean in module numpy:

mean(a, axis=None, dtype=None, out=None, keepdims=<no value>, *, where=<no value>)
    Compute the arithmetic mean along the specified axis.
    
    Returns the average of the array elements.  The average is taken over
    the flattened array by default, otherwise over the specified axis.
    `float64` intermediate and return values are used for integer inputs.
    
    Parameters
    ----------
    a : array_like
        Array containing numbers whose mean is desired. If `a` is not an
        array, a conversion is attempted.
    axis : None or int or tuple of ints, optional
        Axis or axes along which the means are computed. The default is to
        compute the mean of the flattened array.
    
        .. versionadded:: 1.7.0
    
        If this is a tuple of ints, a mean is performed over multiple axes,
        instead of a single axis or all the axes as before.
    dtype : data-type, optional
        Type to use in computing the mean.